/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FormeCenovnik;

import FormeET.FormaPretragaET;
import domen.Cenovnik;
import domen.Korisnik;
import domen.Potvrda;
import domen.StavkaCenovnika;
import enumi.TipObracuna;
import enumi.Valuta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontroler.ClientKontroler;
import tabele.TableModelStavka;

/**
 *
 * @author Zarko
 */
public class FormaIzmeniCen extends javax.swing.JDialog {
    Cenovnik cenovnik;
    Korisnik k;
    
    int brojac=0;
    ArrayList<StavkaCenovnika> nove= new ArrayList<>();

    /**
     * Creates new form FormaIzmeniCen
     */
    public FormaIzmeniCen(JDialog parent, boolean modal, Cenovnik cen, Korisnik k) {
        super(parent, modal);
        initComponents();
        this.k=k;
        cenovnik = cen;
        jTable1.setModel(new TableModelStavka(cenovnik));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumP.setText(String.valueOf(sdf.format(cenovnik.getVaziOd())));
        txtDatumKraj.setText(String.valueOf(sdf.format(cenovnik.getVaziDo())));
        popunicb();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDatumP = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatumKraj = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCena = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Placanje se vrsi:");

        jLabel1.setText("Period vazenja od");

        txtDatumP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jLabel2.setText("do");

        txtDatumKraj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jButton1.setText("Dodaj Stavku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Izmeni Cenovnik");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cena:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Valuta");

        jButton2.setText("Obrisi Stavku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 463, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtDatumP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatumKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txtCena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite polja");
            return;
        }
        
        double price = Double.parseDouble(txtCena.getText());
        Valuta val = (Valuta) jComboBox1.getSelectedItem();
        TipObracuna tip = (TipObracuna) jComboBox2.getSelectedItem();
        TableModelStavka tm = (TableModelStavka) jTable1.getModel();
        StavkaCenovnika stavka = new StavkaCenovnika(-1l, cenovnik, price, val, tip);
        tm.dodajStavku(stavka);
        nove.add(stavka);
        brojac++;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {

            // TODO add your handling code here:
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            if (txtDatumP.getText().isEmpty() || txtDatumKraj.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Datumi nisu uneseni");
                return;
            }
            Date datumOd = sdf.parse(txtDatumP.getText());
            Date datumDo = sdf.parse(txtDatumKraj.getText());

            if(!datumOd.equals(cenovnik.getVaziOd())){
            if (new Date().after(datumOd)) {
                JOptionPane.showMessageDialog(this, "Unesite datum od posle danasnjeg dana!");
                return;
            }}
            
            if (datumOd.after(datumDo)) {
                JOptionPane.showMessageDialog(this, "Greska, datumi zavrsetka ne moze biti pre pocetka");
                return;
            }

            TableModelStavka tm = (TableModelStavka) jTable1.getModel();
            ArrayList<StavkaCenovnika> lista = tm.vratiListu();
//            if(brojac>0){
//                for(int j=0;j<brojac;j++){
//                lista.get(lista.size()-j);
//                ClientKontroler.getInstance().addStavkaCen(cenovnik.getCenovnikId());
//                
//                }
//            
//            
//            }

            

            cenovnik.setVaziOd(datumOd);
            cenovnik.setVaziDo(datumDo);
            cenovnik.setProdavac(k);
            cenovnik.setStavkeC(lista);

            try {
                ClientKontroler.getInstance().UpdateCenovnik(cenovnik);
                JOptionPane.showMessageDialog(this, "Cenovnik je izmenjen");
                FormaPretragaCen fc=(FormaPretragaCen) getParent();
                fc.reakcija();
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        try {
            int row = jTable1.getSelectedRow();
            
            
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "nijedan red nije izabran");
                return;
            }
            
            TableModelStavka mt = (TableModelStavka) jTable1.getModel();
            StavkaCenovnika sc=mt.vratiStavkuCen(row);
            ArrayList<Potvrda> potvrde= ClientKontroler.getInstance().getAllPotvrde();
            for (Potvrda potvrda : potvrde) {
                if(potvrda.getStavkaCenovnika().getStavkaCenId().equals(sc.getStavkaCenId())&&potvrda.getCenovnik().getCenovnikId().equals(cenovnik.getCenovnikId()))
                {
                    JOptionPane.showMessageDialog(this, "Stavka cenovnika ne moze biti obrisana zato sto je u upotrebi");
                    return;
                }
            }
            mt.obrisiRed(row);
        } catch (Exception ex) {
            Logger.getLogger(FormaIzmeniCen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCena;
    private javax.swing.JFormattedTextField txtDatumKraj;
    private javax.swing.JFormattedTextField txtDatumP;
    // End of variables declaration//GEN-END:variables

    private void popunicb() {
     jComboBox1.removeAllItems();
     jComboBox2.removeAllItems();

     for (Valuta val : Valuta.values()) {
         jComboBox1.addItem(val);
     }

     for (TipObracuna tip : TipObracuna.values()) {
         jComboBox2.addItem(tip);
     }

    }
}
