/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FormePotvrde;

import domen.Cenovnik;
import domen.Klijent;
import domen.Potvrda;
import domen.StavkaCenovnika;
import domen.Trotinet;
import forme.KlijentskaForma;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.ClientKontroler;
import tabele.TableModelTrotinet;

/**
 *
 * @author Zarko
 */
public class DetaljiPotvrde extends javax.swing.JDialog {

    Trotinet tr;
    Potvrda izabrana;
    int indeks=0;
    int indeks2=0;
    ArrayList<Klijent> klijenti;
    ArrayList<StavkaCenovnika> pomocna= new ArrayList<>();

    /**
     * Creates new form DetaljiPotvrde
     */
    public DetaljiPotvrde(java.awt.Frame parent, boolean modal, Potvrda p) {
        super(parent, modal);
        initComponents();
        izabrana = p;
        tr = izabrana.getTrotinet();
        jTable1.setModel(new TableModelTrotinet());
        popunisve();
        
        jComboBox2.setSelectedItem(izabrana.getKlijent());
        jComboBox1.setSelectedItem(izabrana.getStavkaCenovnika());
        System.out.println(izabrana.getStavkaCenovnika());
//            try {
//            klijenti = ClientKontroler.getInstance().getAllKlijent();
//        } catch (Exception ex) {
//            Logger.getLogger(DetaljiPotvrde.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            for (Klijent klijent : klijenti) {
//                
//                if(klijent.equals(izabrana.getKlijent())){
//                jComboBox2.setSelectedIndex(indeks);
//                break;
//                }
//                indeks++;
//
//            }
  
            for (StavkaCenovnika stavkaCenovnika : pomocna) {
                if(stavkaCenovnika.getStavkaCenId().equals(izabrana.getStavkaCenovnika().getStavkaCenId())&&stavkaCenovnika.getCenovnik().getCenovnikId().equals(izabrana.getCenovnik().getCenovnikId()))
                {  System.out.println(indeks2);
                jComboBox1.setSelectedIndex(indeks2);
                break;
                }
                System.out.println("ne ne");
                indeks2++;
                
            
        }
            
        jComboBox1.setSelectedItem(izabrana.getStavkaCenovnika());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumP.setText(String.valueOf(sdf.format(izabrana.getDatumOd())));
        txtDatumZ.setText(String.valueOf(sdf.format(izabrana.getDatumDo())));
        jTextField2.setText(Double.toString(izabrana.getCena()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDatumZ = new javax.swing.JFormattedTextField();
        txtDatumP = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DetaljiPotvrde");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("IzmenaPotvrde"));
        jPanel1.setForeground(new java.awt.Color(102, 204, 0));

        jLabel1.setText("Datum pocetka");

        jLabel2.setText("Datum zavrsetka");

        txtDatumZ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        txtDatumP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jLabel3.setText("Iznajmljuje:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Naplacivanje se vrsi:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Izaberi Trotinet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cena:");

        jButton3.setText("Izracunaj cenu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDatumP, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumZ)
                                    .addComponent(jComboBox2, 0, 211, Short.MAX_VALUE))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        TableModelTrotinet tt = (TableModelTrotinet) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "izaberite trotinet");
            return;
        }
        if (txtDatumP.getText().isEmpty() || txtDatumZ.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "popunite sva polja");
            return;

        }
        tr = tt.vratiTrotinet(jTable1.getSelectedRow());


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date DatumOd = sdf.parse(txtDatumP.getText());
            Date DatumDo = sdf.parse(txtDatumZ.getText());

            long millisecondsPerDay = 24 * 60 * 60 * 1000; // Number of milliseconds in a day
            long razlikaIzmedjuDana = DatumDo.getTime() - DatumOd.getTime();
            long razlika = razlikaIzmedjuDana / millisecondsPerDay;
            StavkaCenovnika sta = (StavkaCenovnika) jComboBox1.getSelectedItem();

            double cena = sta.getCena() * razlika;
            jTextField2.setText(String.valueOf(cena));
        } catch (ParseException ex) {
            Logger.getLogger(DetaljiPotvrde.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (tr == null) {
            JOptionPane.showMessageDialog(this, "izaberi trotinet");
        }

        if (txtDatumP.getText().isEmpty() || txtDatumZ.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "popunite sva polja");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        try {
            Date datumOd = sdf.parse(txtDatumP.getText());
            Date datumdo = sdf.parse(txtDatumZ.getText());

            if (datumOd.before(new Date())) {
                JOptionPane.showMessageDialog(this, "Datum mora da bude posle danasnjeg");
                return;
            }

            if (!datumOd.before(datumdo)) {
                JOptionPane.showMessageDialog(this, "DatumDo ne sme biti pre DatumaOd");
                return;
            }

            double cena = Double.parseDouble(jTextField2.getText());
            Klijent k = (Klijent) jComboBox2.getSelectedItem();
            StavkaCenovnika st = (StavkaCenovnika) jComboBox1.getSelectedItem();
            Potvrda potvrda = new Potvrda(izabrana.getPotvrdaId(), datumOd, datumdo, cena, tr, k, st, izabrana.getProdavac(), st.getCenovnik());
            try {
                ClientKontroler.getInstance().UpdatePotvrda(potvrda);
                JOptionPane.showMessageDialog(this, "Potvrda je izmenjena");
                KlijentskaForma kf = (KlijentskaForma) getParent();
                kf.osveziTabelu();
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
//                Logger.getLogger(DodajPotvrduForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ParseException ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JFormattedTextField txtDatumP;
    private javax.swing.JFormattedTextField txtDatumZ;
    // End of variables declaration//GEN-END:variables

    private void popunisve() {
        jTable1.setModel(new TableModelTrotinet());
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        try {
            ArrayList<StavkaCenovnika> stavke;
            ArrayList<StavkaCenovnika> sveStavke;
            ArrayList<Cenovnik> cenovnici = ClientKontroler.getInstance().getAllCenovnik();
            for (Cenovnik cenovnik : cenovnici) {

                stavke = ClientKontroler.getInstance().getAllStavke(cenovnik);
                for (StavkaCenovnika stavka : stavke) {
                    jComboBox1.addItem(stavka);
                    pomocna.add(stavka);

                }
            }
            ArrayList<Klijent> klijenti = ClientKontroler.getInstance().getAllKlijent();
            for (Klijent klijent : klijenti) {
                jComboBox2.addItem(klijent);

            }

            TableModelTrotinet tt = (TableModelTrotinet) jTable1.getModel();

        } catch (Exception ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
